version: '2'
services:
  plex:
    build: .
    container_name: plex
    image: plex:latest
    ports:
      # for access to the Plex Media Server [required]
      - "32400:32400"
      # for access to the Plex DLNA Server
      - "1900:1900/udp"
      - "32469:32469"
      # for controlling Plex Home Theater via Plex Companion
      - "3005:3005"
      # for older Bonjour/Avahi network discovery
      - "5353:5353/udp"
      # for current GDM network discovery
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - /tanker/plex-config:/config
      - /tanker/movies:/movies
      - /tanker/tv:/tv
      - /tanker/music:/music
    env_file:
      - ./plex.env
    restart: always

